### PR TITLE
Blazor viewer

### PR DESCRIPTION
**Pull request by Swimburger**
Here's my Blazor NCrontab tester project. Feel free to change, merge, remove as necessary and let me know if you need anything.
Regarding hosting on GitHub pages, I have [sample GitHub actions workflow to deploy to GitHub pages](https://github.com/Swimburger/BlazorGitHubPagesDemo/blob/master/.github/workflows/main.yml).
I'm planning on writing up a blog post on the deployment to GitHub pages, but that'll be a few weeks.

### CODE REVIEW

**Review by atifaziz — COMMENTED** [review]
Tremendous Niels! I'll start consolidating the two.

**Comment by Swimburger** [comment]
Sounds good to me!

**Comment by Swimburger** [comment]
Here's a tutorial on deploying Blazor to GitHub pages: https://swimburger.net/blog/dotnet/how-to-deploy-aspnet-blazor-webassembly-to-github-pages

**Comment by atifaziz** [comment]
@Swimburger Thanks for sharing. 👍

I'll be progressing on this rather slowly but surely.

**Pull request merged**
