### PR TITLE
Prettify ToString return value

### PR DESCRIPTION
**Pull request by AlexanderButs**
Tried to do as best as can. Any comments are appreciated.

### CODE REVIEW

**Comment by atifaziz** [comment]
@AlexanderButs This puts the original expression at the _schedule_ level when it should really be at the _field_ level so it only solves the problem but partially. I think the expressions should be captured at the field level and the schedule should then just call `ToString` on each of its fields.

**Comment by atifaziz** [comment]
Also, the author/committer for 26ffc8bc08e1cc39737b690ca1a078fb642271ef reads `unknown <alexb@kiepc4298.INTERN.CRYTEK.DE>`, which seems not what you'd intend.

**Comment by AlexanderButs** [comment]
Thanks for Your feedback. I'll try to look at this.

**Comment by rubenmachuca** [comment]
integrar los mejores terminoos del producto

**Comment by atifaziz** [comment]
Closing, assuming stale.

**Pull request closed without merging**
